## METHODE ndarray

In [1]:
import numpy as np

In [2]:
np.random.seed(0)
A  = np.random.randint(0,10,[2,3])
print(A)

[[5 0 3]
 [3 7 9]]


In [3]:
print(A.sum())

27


In [4]:
print(A.sum(axis = 0))

[ 8  7 12]


In [5]:
print(A.sum(axis = 1))

[ 8 19]


In [7]:
print(A.cumsum())

[ 5  5  8 11 18 27]


In [8]:
print(A.cumsum(axis = 0))

[[ 5  0  3]
 [ 8  7 12]]


In [9]:
print(A.cumsum(axis = 1))

[[ 5  5  8]
 [ 3 10 19]]


In [10]:
print(A.cumprod())

[5 0 0 0 0 0]


In [11]:
print(A.cumsum(axis = 0))

[[ 5  0  3]
 [ 8  7 12]]


In [12]:
print(A.cumsum(axis = 1))

[[ 5  5  8]
 [ 3 10 19]]


In [13]:
print(A.min())

0


In [14]:
print(A.min(axis = 0))

[3 0 3]


In [15]:
print(A.min(axis = 1))

[0 3]


In [16]:
print(A.max())

9


In [17]:
print(A.max(axis = 0))

[5 7 9]


In [18]:
print(A.max(axis = 1))

[5 9]


In [19]:
print(A.argmin())

1


In [20]:
print(A.argmin(axis = 0))

[1 0 0]


In [21]:
print(A.argmin(axis = 1))

[1 0]


In [22]:
print(A.argmax(axis = 0))

[0 1 1]


In [25]:
print(A.argsort(axis = 0))

[[0 0 0]
 [1 1 1]]


In [26]:
print(A.argsort(axis = 1))

[[0 1 2]
 [0 1 2]]


## ROUTINE DE NUMPY

In [27]:
print(np.exp(A))

[[1.00000000e+00 2.00855369e+01 1.48413159e+02]
 [2.00855369e+01 1.09663316e+03 8.10308393e+03]]


In [28]:
print(np.sin(A))

[[ 0.          0.14112001 -0.95892427]
 [ 0.14112001  0.6569866   0.41211849]]


In [29]:
print(np.cos(A))

[[ 1.         -0.9899925   0.28366219]
 [-0.9899925   0.75390225 -0.91113026]]


In [30]:
print(np.sinh(A))

[[   0.           10.01787493   74.20321058]
 [  10.01787493  548.31612327 4051.54190208]]


In [31]:
print(np.log(A))

[[      -inf 1.09861229 1.60943791]
 [1.09861229 1.94591015 2.19722458]]


C:\Users\benib\AppData\Local\Temp\ipykernel_13932\2484384912.py:1: RuntimeWarning: divide by zero encountered in log
  print(np.log(A))


## Statistiques

In [38]:
print(A)

[[0 3 5]
 [3 7 9]]


In [39]:
print(A.mean())

4.5


In [40]:
print(A.std())

2.9297326385411577


In [41]:
print(A.var())

8.583333333333334


In [42]:
print(np.corrcoef(A))

[[1.         0.99717646]
 [0.99717646 1.        ]]


In [43]:
print(np.corrcoef(A)[0,1])

0.997176464952738


In [44]:
np.unique(A, return_counts = True)

(array([0, 3, 5, 7, 9]), array([1, 2, 1, 1, 1], dtype=int64))

In [45]:
np.random.seed(0)
A  = np.random.randint(0,10,[5,5])
print(A)

[[5 0 3 3 7]
 [9 3 5 2 4]
 [7 6 8 8 1]
 [6 7 7 8 1]
 [5 9 8 9 4]]


In [48]:
values, counts = np.unique(A, return_counts = True)

In [49]:
print(counts)

[1 2 1 3 2 3 2 4 4 3]


In [50]:
print(counts.argsort())

[0 2 1 4 6 3 5 9 7 8]


In [51]:
print(values[counts.argsort()])

[0 2 1 4 6 3 5 9 7 8]


In [52]:
for i,j in zip(values[counts.argsort()], counts[counts.argsort()]):
    print(f'valeur {i} apparait {j}')

valeur 0 apparait 1
valeur 2 apparait 1
valeur 1 apparait 2
valeur 4 apparait 2
valeur 6 apparait 2
valeur 3 apparait 3
valeur 5 apparait 3
valeur 9 apparait 3
valeur 7 apparait 4
valeur 8 apparait 4


## NAN Corrections

In [53]:
A = np.random.randn(5,5)
A[0,2] = np.nan
A[4,3] = np.nan
print(A)

[[ 0.44386323  0.33367433         nan -0.20515826  0.3130677 ]
 [-0.85409574 -2.55298982  0.6536186   0.8644362  -0.74216502]
 [ 2.26975462 -1.45436567  0.04575852 -0.18718385  1.53277921]
 [ 1.46935877  0.15494743  0.37816252 -0.88778575 -1.98079647]
 [-0.34791215  0.15634897  1.23029068         nan -0.38732682]]


In [54]:
print(np.nanmean(A))

0.010707879575141632


In [56]:
print(np.nanstd(A))

1.1017518326683546


In [57]:
print(np.nanvar(A))

1.213857100788078


In [58]:
print(np.isnan(A))

[[False False  True False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False  True False]]


In [59]:
print(np.isnan(A).sum())

2


In [60]:
print(np.isnan(A).sum()/A.size)

0.08


In [61]:
print(np.isnan(A))

[[False False  True False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False  True False]]


In [62]:
A[np.isnan(A)] = 0
print(A)

[[ 0.44386323  0.33367433  0.         -0.20515826  0.3130677 ]
 [-0.85409574 -2.55298982  0.6536186   0.8644362  -0.74216502]
 [ 2.26975462 -1.45436567  0.04575852 -0.18718385  1.53277921]
 [ 1.46935877  0.15494743  0.37816252 -0.88778575 -1.98079647]
 [-0.34791215  0.15634897  1.23029068  0.         -0.38732682]]


## Algèbre Lineaire

In [63]:
A = np.ones((2,3))
B = np.ones((3,2))
print(A)

[[1. 1. 1.]
 [1. 1. 1.]]


In [64]:
print(B)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [65]:
 print(A.T)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [66]:
print(A.dot(B))

[[3. 3.]
 [3. 3.]]


In [67]:
print(B.dot(A))

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [68]:
A = np.random.randint(0,10, [3,3])
print(A)

[[3 5 9]
 [4 4 6]
 [4 4 3]]


In [69]:
print(np.linalg.det(A))

23.999999999999993


In [70]:
print(np.linalg.inv(A))

[[-0.5         0.875      -0.25      ]
 [ 0.5        -1.125       0.75      ]
 [-0.          0.33333333 -0.33333333]]


In [71]:
print(np.linalg.eig(A))

(array([13.58872344, -3.        , -0.58872344]), array([[-6.70561268e-01, -8.32050294e-01,  6.04408531e-01],
       [-5.73889829e-01,  1.85511715e-16, -7.73940635e-01],
       [-4.70104297e-01,  5.54700196e-01,  1.88960901e-01]]))


## EXERCICE
Standardisez la matrice A sur chaque colonne
    Resultat : chaque ligne doit avoir moyenne = 0 et écart type = 1

In [72]:
np.random.seed(0)

In [73]:
A= np.random.randint(0,100, [10,5])
print(A)

[[44 47 64 67 67]
 [ 9 83 21 36 87]
 [70 88 88 12 58]
 [65 39 87 46 88]
 [81 37 25 77 72]
 [ 9 20 80 69 79]
 [47 64 82 99 88]
 [49 29 19 19 14]
 [39 32 65  9 57]
 [32 31 74 23 35]]


In [74]:
D = (A-A.mean(axis =0)) / A.std(axis = 0)

In [75]:
print(D)

[[-0.02206157  0.          0.13173823  0.72539252  0.10755798]
 [-1.56637126  1.61579632 -1.48676006 -0.33034307  0.96802178]
 [ 1.12513992  1.84021247  1.03508612 -1.14768676 -0.27965074]
 [ 0.90452425 -0.35906585  0.99744662  0.0102168   1.01104497]
 [ 1.6104944  -0.44883231 -1.33620208  1.0659524   0.32267393]
 [-1.56637126 -1.21184724  0.73397016  0.7935045   0.62383626]
 [ 0.11030784  0.76301493  0.80924915  1.81518411  1.01104497]
 [ 0.1985541  -0.80789816 -1.56203905 -0.90929485 -2.17267111]
 [-0.24267724 -0.67324847  0.16937773 -1.24985473 -0.32267393]
 [-0.55153918 -0.7181317   0.50813319 -0.77307091 -1.26918412]]


In [76]:
print(D.mean(axis = 0))

[-2.22044605e-17 -4.44089210e-17  0.00000000e+00 -1.22124533e-16
 -4.44089210e-17]


In [77]:
print(D.std(axis = 0))

[1. 1. 1. 1. 1.]
