In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.linear_model import SGDClassifier

## SimpleImputer

In [3]:
from sklearn.impute import SimpleImputer

In [4]:
X = np.array([
    [10,3],
    [0,4],
    [5,3],
    [np.nan , 3]
])

In [5]:
imputer = SimpleImputer(missing_values = np.nan,
             strategy = 'mean')
imputer.fit_transform(X)

array([[10.,  3.],
       [ 0.,  4.],
       [ 5.,  3.],
       [ 5.,  3.]])

In [6]:
X_test = np.array([[12,5],
                  [40,2],
                  [5,5],
                  [np.nan , np.nan]])
imputer.fit_transform(X_test)

array([[12.,  5.],
       [40.,  2.],
       [ 5.,  5.],
       [19.,  4.]])

## KNNImputer

In [10]:
from sklearn.impute import KNNImputer , MissingIndicator

In [9]:
imputer = KNNImputer(n_neighbors = 1)
imputer.fit_transform(X)

array([[10.,  3.],
       [ 0.,  4.],
       [ 5.,  3.],
       [10.,  3.]])

## MissingIndicator

In [12]:
MissingIndicator().fit_transform(X_test)

array([[False, False],
       [False, False],
       [False, False],
       [ True,  True]])